name: Testing React Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Node install
        uses: actions/setup-node@v4
      - name: install packages
        run: npm ci
      - name: run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install the Node.js
        uses: actions/setup-node@v4
      - name: Install the packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
